### ISSUE TITLE
Fix System.Buffers dependency

### ISSUE THREAD

**Issue by vermorel** [Lokad/BitcoinNet#1]
On my config (VS 2017), most unit tests seem to fail against the follow-up error message:

```
System.TypeInitializationException
The type initializer for 'BitcoinNet.Network' threw an exception.
   at BitcoinNet.Network.get_Main()
   at BitcoinNet.Tests.ChainTests.CanBuildChain() in C:\Users\...\code\bitcoin.net\BitcoinNet.Tests\ChainTests.cs:line 164

System.IO.FileLoadException
Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at BitcoinNet.Crypto.HashStream..ctor()
   at BitcoinNet.Transaction.CreateHashStream()
   at BitcoinNet.Transaction.GetHash()
   at BitcoinNet.Block.<>c.<GetMerkleRoot>b__6_0(Transaction t)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BitcoinNet.MerkleNode.GetRoot(IEnumerable`1 leafs)
   at BitcoinNet.Block.GetMerkleRoot()
   at BitcoinNet.Block.UpdateMerkleRoot()
   at BitcoinNet.Network.CreateGenesisBlock(String pszTimestamp, Script genesisOutputScript, UInt32 nTime, UInt32 nNonce, UInt32 nBits, Int32 nVersion, Money genesisReward)
   at BitcoinNet.Network.CreateGenesisBlock(UInt32 nTime, UInt32 nNonce, UInt32 nBits, Int32 nVersion, Money genesisReward)
   at BitcoinNet.Network.InitMain()
   at BitcoinNet.Network..cctor()
```

**Comment by osman-turan** [comment]
Can you please test it with #28 ?

**Comment by vermorel** [comment]
Looks good now!
